"""
RoamDigi proposal renderer.

There are no preset templates. You compose the proposal at run time from the web
UI: paste the email data (subject + body) and the agent formats it into a clean,
professional email — adding a formal greeting that uses the agency name and
turning the body into well-spaced paragraphs and bullet lists.

The subject + body are stored in settings as custom_subject / custom_body.

The greeting line is generated by the agent — never typed into the body. It is a
formal salutation that uses the agency name (e.g. "Dear Sir/Madam at Skyline
Travels,"), or the contact's first name when one is confidently known.

Optional placeholders you may use in the body, filled per recipient at send time:
    [Greeting]  (where the auto greeting goes; prepended if omitted)
    [Agency Name], [Your Name], [Title],
    [X]  (commission number),
    [partner commission]  (phrase),
    [Mobile app line]
"""
import re

CUSTOM_DRAFT = "custom"
DEFAULT_DRAFT = CUSTOM_DRAFT

# No preset templates — every proposal is composed at run time.
DRAFTS = {}


def draft_list(settings=None):
    """Single compose-now entry for the UI (presets were removed)."""
    settings = settings or {}
    return [{
        "id": CUSTOM_DRAFT,
        "name": "Composed proposal",
        "blurb": "Paste your email data; the agent formats it and adds a formal greeting.",
        "subject": (settings.get("custom_subject") or "").strip(),
    }]


def clean_agency_name(raw):
    """Trim address junk that got concatenated into some agency names."""
    if not raw:
        return ""
    s = re.sub(r"\s+", " ", str(raw)).strip()
    # Cut at the first comma (addresses usually follow)
    s = s.split(",")[0].strip()
    # Drop a trailing hyphenated address/sector code like "G-E", "G-9", "F-7"
    # (requires the hyphen so real suffixes like "Ltd"/"Pvt" are kept).
    s = re.sub(r"\s+[A-Za-z]{1,3}-[A-Za-z0-9]{1,4}$", "", s).strip()
    return s or str(raw).strip()


def first_name_from(name, email):
    """
    Best-effort first name for the greeting.
    Most rows are brand/role mailboxes (info@, sales@, goglobal@), so this is
    intentionally conservative: it only returns a name for clear person-style
    locals like "abdul.manan@" or "ahmed_khan@". Otherwise it returns '' and the
    caller falls back to the configured greeting (e.g. "there").
    """
    if not email:
        return ""
    local = email.split("@")[0].lower()
    if any(c.isdigit() for c in local):
        return ""
    # Require a firstname<sep>lastname pattern — single-token locals are usually
    # the brand/role, not a person.
    parts = [p for p in re.split(r"[._-]", local) if p]
    if len(parts) >= 2 and parts[0].isalpha() and len(parts[0]) >= 2 and len(parts[1]) >= 2:
        generic = {
            "info", "sales", "contact", "admin", "office", "support", "booking",
            "bookings", "enquiry", "enquiries", "inquiry", "ceo", "hello", "no",
            "reservations", "travel", "tours", "marketing", "help", "team", "mail",
        }
        if parts[0] not in generic:
            return parts[0].capitalize()
    return ""


def greeting_line(recipient, settings):
    """
    Build the formal salutation the agent prepends to every proposal.

    The greeting always uses the AGENCY NAME — never a person's first name:
        agency known  -> "Dear Skyline Travels,"
        no agency     -> "Dear Sir/Madam,"
    """
    agency = clean_agency_name(recipient.get("agency_name") or recipient.get("name") or "")
    if agency:
        return f"Dear {agency},"
    fallback = (settings.get("greeting_fallback") or "").strip()
    # "there" was the old casual default; keep the greeting formal regardless.
    if not fallback or fallback.lower() == "there":
        fallback = "Sir/Madam"
    return f"Dear {fallback},"


def _mobile_app_line(settings):
    appstore = (settings.get("app_store_url") or "").strip()
    play = (settings.get("play_store_url") or "").strip()
    if appstore and play:
        return f"Mobile app: {appstore} | {play}"
    if appstore:
        return f"Mobile app (iOS): {appstore}"
    if play:
        return f"Mobile app (Android): {play}"
    return ""  # nothing configured -> drop the line entirely


def render(draft_id, recipient, settings):
    """
    Returns dict: {subject, body, html, unresolved:[...]}
    `recipient` is a dict with at least agency_name, first_name, email.
    `settings` carries sender_name, title, commission, partner_commission,
    greeting_fallback, app_store_url, play_store_url, and — for the custom
    proposal composed at run time — custom_subject / custom_body.
    """
    # There are no presets — the proposal is always the composed one.
    draft = DRAFTS.get(draft_id)
    if draft:
        subject_t = draft["subject"]
        body_t = draft["body"]
    else:
        subject_t = (settings.get("custom_subject") or "").strip()
        body_t = (settings.get("custom_body") or "").strip()

    agency = clean_agency_name(recipient.get("agency_name") or recipient.get("name") or "")
    greeting = greeting_line(recipient, settings)

    repl = {
        "[Greeting]": greeting,
        "[Agency Name]": agency or "your agency",
        # Never substitute a person's name; fall back to the agency name.
        "[First Name]": agency or "your agency",
        "[Your Name]": (settings.get("sender_name") or "").strip(),
        "[Title]": (settings.get("title") or "").strip(),
        "[X]": str(settings.get("commission") or "").strip(),
        "[partner commission]": (settings.get("partner_commission") or "partner commission program").strip(),
        "[Mobile app line]": _mobile_app_line(settings),
    }

    def apply(text):
        for k, v in repl.items():
            text = text.replace(k, v)
        # If the mobile-app line was dropped, remove the now-empty line cleanly.
        text = re.sub(r"\n[ \t]*\n[ \t]*\n", "\n\n", text)
        return text

    subject = apply(subject_t)
    body = apply(body_t).strip()

    # The agent always owns the greeting: if the body has no [Greeting] marker
    # (e.g. a custom proposal typed without one), prepend the formal salutation.
    # First strip any salutation the composer typed (e.g. "Dear ...", "Hi ...")
    # so we never end up with a wrong or duplicated greeting.
    if "[Greeting]" not in body_t:
        body = re.sub(r"^\s*(dear|hi|hello|hey|greetings)\b[^\n]*\n+", "",
                      body, count=1, flags=re.IGNORECASE)
        body = f"{greeting}\n\n{body}".strip() if body.strip() else greeting

    # Detect any placeholder we failed to fill (e.g. empty sender name).
    unresolved = sorted(set(re.findall(r"\[[^\]]+\]", subject + "\n" + body)))

    return {
        "subject": subject,
        "body": body,
        "html": _email_template(_body_inner_html(body), settings),
        "unresolved": unresolved,
    }


# ---------------------------------------------------------------------------
# HTML email template
# ---------------------------------------------------------------------------
# Brand assets used to dress the proposal in a professional, attractive layout.
# Each is overridable from settings via a "brand_<key>" entry.
BRAND = {
    "name": "RoamDigi",
    "tagline": "Travel smart, stay connected",
    "website": "https://www.roamdigi.com",
    "email": "info@roamdigi.com",
    "phone": "+1 585 282 6724",
}


def _body_inner_html(body):
    """
    Convert the plain-text proposal body into clean inner HTML: paragraphs,
    proper <ul> bullet lists, and a quieter style for the signature block.
    Returns just the inner markup (the email template provides the container).
    """
    import html as _html

    def linkify(line):
        line = _html.escape(line)
        line = re.sub(
            r"(https?://[^\s|]+)",
            r'<a href="\1" style="color:#1a73e8;text-decoration:none;">\1</a>',
            line,
        )
        line = re.sub(
            r"([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})",
            r'<a href="mailto:\1" style="color:#1a73e8;text-decoration:none;">\1</a>',
            line,
        )
        return line

    closings = ("best regards", "warm regards", "kind regards", "regards",
                "sincerely", "thanks", "thank you", "yours faithfully",
                "yours sincerely")

    def is_bullet(line):
        return line.lstrip().startswith(("•", "- "))

    parts = []
    sig_started = False
    for bi, block in enumerate(body.split("\n\n")):
        lines = block.split("\n")
        # Treat everything from the closing line onward as the signature block.
        first = lines[0].strip().rstrip(",").lower() if lines else ""
        if not sig_started and first in closings:
            sig_started = True

        i = 0
        para_style = ("margin:0 0 4px 0;color:#5f6b7a;font-size:14px;"
                      if sig_started else "margin:0 0 16px 0;")
        # The very first paragraph is the greeting — give it a touch more weight.
        if bi == 0 and not sig_started:
            para_style = "margin:0 0 16px 0;font-weight:700;color:#0d2a4a;"
        while i < len(lines):
            if is_bullet(lines[i]):
                items = []
                while i < len(lines) and is_bullet(lines[i]):
                    items.append(
                        '<li style="margin:0 0 8px 0;">'
                        + linkify(lines[i].lstrip().lstrip("•-").strip()) + "</li>"
                    )
                    i += 1
                parts.append(
                    '<ul style="margin:0 0 16px 0;padding-left:20px;">'
                    + "".join(items) + "</ul>"
                )
            else:
                run = []
                while i < len(lines) and not is_bullet(lines[i]):
                    run.append(linkify(lines[i]))
                    i += 1
                parts.append(f'<p style="{para_style}">' + "<br>".join(run) + "</p>")

    return "".join(parts)


def _email_template(inner_html, settings):
    """Wrap the proposal body in a polished, email-client-safe HTML shell."""
    s = settings or {}

    def pick(key):
        return (s.get("brand_" + key) or "").strip() or BRAND[key]

    name, tagline = pick("name"), pick("tagline")
    website, email, phone = pick("website"), pick("email"), pick("phone")
    website_display = re.sub(r"^https?://", "", website).rstrip("/")

    appstore = (s.get("app_store_url") or "").strip()
    play = (s.get("play_store_url") or "").strip()
    badges = []
    if appstore:
        badges.append(f'<a href="{appstore}" style="color:#1a73e8;text-decoration:none;">App Store</a>')
    if play:
        badges.append(f'<a href="{play}" style="color:#1a73e8;text-decoration:none;">Google Play</a>')
    apps_line = (
        f'<div style="margin-top:6px;">Get the app: {" &nbsp;·&nbsp; ".join(badges)}</div>'
        if badges else ""
    )

    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="x-apple-disable-message-reformatting">
</head>
<body style="margin:0;padding:0;background:#eef2f7;-webkit-text-size-adjust:100%;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#eef2f7;">
  <tr><td align="center" style="padding:24px 12px;">
    <table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0"
           style="width:600px;max-width:600px;background:#ffffff;border-radius:14px;overflow:hidden;
                  box-shadow:0 4px 18px rgba(13,42,74,.10);font-family:Arial,Helvetica,sans-serif;">
      <!-- header -->
      <tr><td style="background:#0d2a4a;background:linear-gradient(135deg,#0d2a4a 0%,#1a73e8 100%);padding:28px 32px;">
        <div style="font-size:24px;font-weight:800;color:#ffffff;letter-spacing:.3px;">{name}</div>
        <div style="font-size:13px;color:#cfe0fb;margin-top:5px;">{tagline}</div>
      </td></tr>
      <!-- body -->
      <tr><td style="padding:32px;color:#202124;font-size:15px;line-height:1.65;
                     font-family:Arial,Helvetica,sans-serif;">{inner_html}</td></tr>
      <!-- call to action -->
      <tr><td style="padding:0 32px 28px;">
        <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr>
          <td align="center" style="border-radius:8px;background:#1a73e8;">
            <a href="{website}" style="display:inline-block;padding:13px 26px;color:#ffffff;font-size:14px;
               font-weight:700;text-decoration:none;border-radius:8px;font-family:Arial,Helvetica,sans-serif;">
               Visit {name} &rarr;</a>
          </td>
        </tr></table>
      </td></tr>
      <!-- footer -->
      <tr><td style="padding:22px 32px 28px;border-top:1px solid #eceff3;background:#fafbfd;
                     color:#7a869a;font-size:12px;line-height:1.7;font-family:Arial,Helvetica,sans-serif;">
        <div>
          <a href="{website}" style="color:#1a73e8;text-decoration:none;">{website_display}</a>
          &nbsp;·&nbsp; <a href="mailto:{email}" style="color:#1a73e8;text-decoration:none;">{email}</a>
          &nbsp;·&nbsp; {phone}
        </div>
        {apps_line}
        <div style="margin-top:12px;color:#9aa6b8;">&copy; {name}. {tagline}.</div>
      </td></tr>
    </table>
  </td></tr>
</table>
</body>
</html>"""
